---
output: github_document
---

# Introduction to R

### Course Description

Welcome to Intro to R!  This short course provides a gentle, hands-on introduction to the R programming language for data science applications. You will learn the fundamental skills required to import, tidy, transform, manipulate, and visualize real world consumer data. The following is an outline of the material covered in this training:

__Day 1__
  
| Topic | Time |
|:------|:------:|
| [Intro & Fundamentals](https://uc-r.github.io/Intro-R/day-1a-intro.html) | 9:00 - 10:00 |
| [Importing data](https://uc-r.github.io/Intro-R/day-1b-import.html) | 10:00 - 10:30 |
| Break | 10:30 - 10:45 |
| [Data transformation](https://uc-r.github.io/Intro-R/day-1c-transform.html) | 10:45 - 12:00 |
| Lunch | 12:00 - 1:00 |
| [Review](https://uc-r.github.io/Intro-R/day-1d-review.html) | 1:00-1:30 |
| [Data visualization](https://uc-r.github.io/Intro-R/day-1e-visualization.html) | 1:30-2:30 |
| Break | 2:30-2:45 |
| [Case study](https://uc-r.github.io/Intro-R/day-1f-case-study.html) | 2:45-4:00 |
| Q&A | 4:00-4:30 |

__Day 2__
 
| Topic | Time |
|:------|:------:|
| [Review](https://uc-r.github.io/Intro-R/day-2a-intro.html) | 9:00-10:00 |
| [Data types](https://uc-r.github.io/Intro-R/day-2b-data-types.html) | 10:00-10:45 |
| Break | 10:45 - 11:00 |
| [Tidy data](https://uc-r.github.io/Intro-R/day-2c-tidy.html) | 11:00-12:00 |
| Lunch | 12:00 - 1:00 |
| [Joining data](https://uc-r.github.io/Intro-R/day-2d-joins.html) | 1:00-1:45 |
| [Data structures](https://uc-r.github.io/Intro-R/day-2e-data-structures.html) | 1:45-2:30 |
| Break | 2:30-2:45 |
| Case study | 2:45-4:00 |
| Q&A | 4:00-4:30 |

### Course Preparation

To prepare for this course please complete the following ___prior___ to the day of class:

1. Download the class material [here](https://www.dropbox.com/sh/atlmrrqnxadlv2b/AACmHEKViL-eFeH9itgc5E9oa?dl=1). This will provide you with the data and R scripts to follow along during class.  I have also included handy cheat sheets that you can reference throughout different sections.

2. All slides are available via the hyperlinks in the schedule above so that you can follow along.

3. Please have the following versions of R and RStudio installed.  If you have an earlier version of R that is at least version 3.4.5 or later you should be ok but its best to be as current as possible.
    - R:  3.5.1 [[download latest version](https://cran.r-project.org/)]
    - RStudio: 1.1.463 [[download latest version](https://www.rstudio.com/products/rstudio/download/#download)]
    - Visit [here](http://uc-r.github.io/basics#installation) if you need installation instructions


If you have any specific questions prior to the class you can reach out to Brad Boehmke directly at [bradleyboehmke@gmail.com](mailto:bradleyboehmke@gmail.com)

